# Generated by Django 5.0.3 on 2024-04-10 10:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Piso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'piso CPV',
                'verbose_name_plural': 'pisos CPV',
            },
        ),
        migrations.CreateModel(
            name='Torre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name='Nombre')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'torre CPV',
                'verbose_name_plural': 'torres CPV',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('type_local', models.CharField(blank=True, choices=[('CO', 'Consultorio'), ('OT', 'Otro')], max_length=2, null=True, verbose_name='Tipo Local')),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.piso', verbose_name='Piso')),
                ('tower', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.torre', verbose_name='Torre')),
            ],
            options={
                'verbose_name': 'localidad CPV',
                'verbose_name_plural': 'localidades CPV',
                'unique_together': {('tower', 'floor', 'type_local', 'local')},
            },
        ),
    ]
