# Generated by Django 5.0.3 on 2024-04-16 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='localidad',
            options={'verbose_name': 'localidad', 'verbose_name_plural': 'localidades'},
        ),
        migrations.AlterModelOptions(
            name='piso',
            options={'verbose_name': 'piso', 'verbose_name_plural': 'pisos'},
        ),
        migrations.AlterModelOptions(
            name='torre',
            options={'verbose_name': 'torre', 'verbose_name_plural': 'torres'},
        ),
    ]
