# Generated by Django 5.0.3 on 2024-04-03 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0003_alter_historicallocalidad_local_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='torre',
            unique_together={('name', 'status')},
        ),
    ]
