# Generated by Django 5.0.3 on 2024-04-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0004_alter_torre_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltorre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
