# Generated by Django 5.0.3 on 2024-04-03 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0005_alter_historicaltorre_name_alter_torre_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='torre',
            unique_together=set(),
        ),
    ]
