# Generated by Django 5.0.3 on 2024-04-03 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0006_alter_torre_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpiso',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='piso',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
