# Generated by Django 5.0.3 on 2024-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0007_alter_historicalpiso_name_alter_piso_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpiso',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicaltorre',
            name='name',
            field=models.CharField(db_index=True, max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='piso',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
    ]
