# Generated by Django 5.0.3 on 2024-04-03 16:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0009_alter_historicalpiso_name_alter_historicaltorre_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='torre',
            name='unique_if_status_not_false',
        ),
        migrations.AddConstraint(
            model_name='piso',
            constraint=models.UniqueConstraint(condition=models.Q(('status', True)), fields=('name',), name='floor_unique_if_status_not_false'),
        ),
        migrations.AddConstraint(
            model_name='torre',
            constraint=models.UniqueConstraint(condition=models.Q(('status', True)), fields=('name',), name='tower_unique_if_status_not_false'),
        ),
    ]
