# Generated by Django 5.0.3 on 2024-04-05 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0011_remove_historicallocalidad_changed_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='location_cpv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.localidad', verbose_name='Localidad CPV'),
        ),
    ]
