# Generated by Django 5.0.3 on 2024-04-05 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0012_alter_piso_name_alter_torre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localidad',
            name='local',
            field=models.CharField(max_length=100),
        ),
    ]
