# Generated by Django 5.0.3 on 2024-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0014_alter_localidad_floor_alter_localidad_tower'),
    ]

    operations = [
        migrations.AlterField(
            model_name='piso',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='torre',
            name='name',
            field=models.CharField(max_length=20, unique=True, verbose_name='Nombre'),
        ),
    ]
