# Generated by Django 5.0.3 on 2024-04-05 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0015_alter_piso_name_alter_torre_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together={('tower', 'floor', 'type_local', 'local')},
        ),
    ]
