# Generated by Django 5.0.3 on 2024-04-05 14:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0016_alter_localidad_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='localidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='floor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.piso', verbose_name='Piso'),
        ),
        migrations.AlterField(
            model_name='localidad',
            name='tower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.torre', verbose_name='Torre'),
        ),
    ]
