# Generated by Django 5.0.3 on 2024-04-05 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0018_alter_localidad_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together={('its_cpv', 'location'), ('its_cpv', 'location_cpv')},
        ),
    ]
