# Generated by Django 5.0.3 on 2024-04-05 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0019_alter_ubicacion_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piso',
            unique_together={('status', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='torre',
            unique_together={('status', 'name')},
        ),
    ]
