# Generated by Django 5.0.3 on 2024-04-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0020_alter_piso_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='piso',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='torre',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ubicacion',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='location',
            field=models.TextField(blank=True, null=True, unique=True, verbose_name='Direccion'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='location_cpv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.localidad', unique=True, verbose_name='Localidad CPV'),
        ),
    ]
