# Generated by Django 5.0.3 on 2024-04-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0021_alter_piso_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='location_cpv',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.localidad', verbose_name='Localidad CPV'),
        ),
    ]
