# Generated by Django 5.0.3 on 2024-04-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubicaciones', '0022_alter_ubicacion_location_cpv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Direccion'),
        ),
    ]
