# Generated by Django 5.0.3 on 2024-04-10 10:12

import apps.base.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('identification', models.CharField(max_length=9, unique=True, verbose_name='Cédula de identidad')),
                ('identification_nature', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO')], default='V', max_length=1, verbose_name='Naturaleza de la cedula')),
                ('rif', models.CharField(max_length=10, unique=True, verbose_name='RIF')),
                ('identification_rif', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('J', 'JURIDICO'), ('P', 'PASAPORTE'), ('G', 'GOBIERNO')], default='V', max_length=1, verbose_name='Naturaleza del rif')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=1, verbose_name='Sexo')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo apellido')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato de numero telefonico: '9999-9999999'.", regex='^\\d{4}\\-?1?\\d{7,15}$')], verbose_name='Numero telefonico')),
                ('photo', models.ImageField(blank=True, upload_to='medicos', verbose_name='Foto')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
            },
            bases=(apps.base.models.PersonMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.especialidad')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.medico')),
            ],
            options={
                'verbose_name': 'especialidad del medico',
                'verbose_name_plural': 'especialidades del medico',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='specialty',
            field=models.ManyToManyField(through='medicos.MedicoEspecialidad', to='medicos.especialidad', verbose_name='Especialidad'),
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('its_cpv', models.BooleanField(verbose_name='¿Es CPV?')),
                ('location', models.TextField(blank=True, null=True, verbose_name='Direccion')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
                ('location_cpv', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.localidad', verbose_name='Localidad CPV')),
            ],
            options={
                'verbose_name': 'ubicacion',
                'verbose_name_plural': 'ubicaciones',
            },
        ),
        migrations.CreateModel(
            name='MedicoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.medico')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.ubicacion')),
            ],
            options={
                'verbose_name': 'ubicacion del medico',
                'verbose_name_plural': 'ubicaciones del medico',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='location',
            field=models.ManyToManyField(through='medicos.MedicoUbicacion', to='medicos.ubicacion', verbose_name='Ubicacion'),
        ),
    ]
