# Generated by Django 5.0.3 on 2024-03-18 15:20

import apps.base.models
import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubicaciones', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'especialidad',
                'verbose_name_plural': 'especialidades',
            },
        ),
        migrations.CreateModel(
            name='HistoricalEspecialidad',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('name', models.CharField(max_length=30, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripcion')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical especialidad',
                'verbose_name_plural': 'historical especialidades',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalMedico',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(db_index=True, max_length=5, verbose_name='Codigo')),
                ('identification', models.CharField(db_index=True, max_length=9, verbose_name='Cédula de identidad')),
                ('identification_nature', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO')], default='V', max_length=1, verbose_name='Naturaleza de la cedula')),
                ('rif', models.CharField(db_index=True, max_length=10, verbose_name='RIF')),
                ('identification_rif', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('J', 'JURIDICO'), ('P', 'PASAPORTE'), ('G', 'GOBIERNO')], default='V', max_length=1, verbose_name='Naturaleza del rif')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=1, verbose_name='Sexo')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo apellido')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato de numero telefonico: '9999-9999999'.", regex='^\\d{4}\\-?1?\\d{7,15}$')], verbose_name='Numero telefonico')),
                ('photo', models.TextField(blank=True, max_length=100, verbose_name='Foto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('changed_by', models.ForeignKey(blank=True, db_constraint=False, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical medico',
                'verbose_name_plural': 'historical medicos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, help_text='Activo✅ / Inactivo ❌', verbose_name='Estado')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('deleted_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de Eliminación')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Codigo')),
                ('identification', models.CharField(max_length=9, unique=True, verbose_name='Cédula de identidad')),
                ('identification_nature', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO')], default='V', max_length=1, verbose_name='Naturaleza de la cedula')),
                ('rif', models.CharField(max_length=10, unique=True, verbose_name='RIF')),
                ('identification_rif', models.CharField(choices=[('V', 'VENEZOLANO'), ('E', 'EXTRANJERO'), ('J', 'JURIDICO'), ('P', 'PASAPORTE'), ('G', 'GOBIERNO')], default='V', max_length=1, verbose_name='Naturaleza del rif')),
                ('sex', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=1, verbose_name='Sexo')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primer nombre')),
                ('second_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo nombre')),
                ('last_name', models.CharField(max_length=20, verbose_name='Primer apellido')),
                ('second_last_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='Segundo apellido')),
                ('phone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Formato de numero telefonico: '9999-9999999'.", regex='^\\d{4}\\-?1?\\d{7,15}$')], verbose_name='Numero telefonico')),
                ('photo', models.ImageField(blank=True, upload_to='', verbose_name='Foto')),
                ('changed_by', models.ForeignKey(blank=True, help_text='El último usuario en alterar el registro', null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='Cambiado por (Usuario)')),
            ],
            options={
                'verbose_name': 'medico',
                'verbose_name_plural': 'medicos',
            },
            bases=(apps.base.models.PersonMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MedicoEspecialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.especialidad')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.medico')),
            ],
            options={
                'verbose_name': 'especialidad del medico',
                'verbose_name_plural': 'especialidades de los medicos',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='specialty',
            field=models.ManyToManyField(through='medicos.MedicoEspecialidad', to='medicos.especialidad', verbose_name='Especialidad'),
        ),
        migrations.CreateModel(
            name='MedicoUbicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medico', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='medicos.medico')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='ubicaciones.ubicacion')),
            ],
            options={
                'verbose_name': 'ubicacion del medico',
                'verbose_name_plural': 'ubicaciones de los medicos',
            },
        ),
        migrations.AddField(
            model_name='medico',
            name='location',
            field=models.ManyToManyField(through='medicos.MedicoUbicacion', to='ubicaciones.ubicacion', verbose_name='Ubicacion'),
        ),
    ]
