# Generated by Django 5.0.3 on 2024-03-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='photo',
            field=models.ImageField(blank=True, upload_to='medicos', verbose_name='Foto'),
        ),
    ]
