# Generated by Django 5.0.3 on 2024-04-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='code',
            field=models.CharField(max_length=5, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='its_cpv',
            field=models.BooleanField(verbose_name='¿La ubicacion es CPV?'),
        ),
    ]
