# Generated by Django 5.0.3 on 2024-03-21 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_photo'),
        ('ubicaciones', '0003_alter_historicallocalidad_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='location',
            field=models.ManyToManyField(related_name='Medico', through='medicos.MedicoUbicacion', to='ubicaciones.ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='specialty',
            field=models.ManyToManyField(related_name='Medico', through='medicos.MedicoEspecialidad', to='medicos.especialidad', verbose_name='Especialidad'),
        ),
    ]
