# Generated by Django 5.0.3 on 2024-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0002_alter_medico_code_alter_ubicacion_its_cpv'),
        ('medicos', '0002_alter_ubicacion_its_cpv'),
    ]

    operations = [
    ]
