# Generated by Django 5.0.3 on 2024-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_alter_medico_location_alter_medico_specialty'),
        ('ubicaciones', '0008_alter_historicalpiso_name_alter_historicaltorre_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especialidad',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalespecialidad',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='location',
            field=models.ManyToManyField(through='medicos.MedicoUbicacion', to='ubicaciones.ubicacion', verbose_name='Ubicacion'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='specialty',
            field=models.ManyToManyField(through='medicos.MedicoEspecialidad', to='medicos.especialidad', verbose_name='Especialidad'),
        ),
    ]
