# Generated by Django 5.0.3 on 2024-04-23 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0003_merge_20240423_0930'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='identification_rif',
            new_name='rif_nature',
        ),
    ]
