# Generated by Django 5.0.3 on 2024-04-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0004_rename_identification_rif_medico_rif_nature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medico',
            old_name='specialty',
            new_name='specialties',
        ),
    ]
