# Generated by Django 5.0.3 on 2024-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_alter_especialidad_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='especialidad',
            name='specialty_name_unique_if_status_not_false',
        ),
        migrations.RemoveConstraint(
            model_name='medico',
            name='medic_unique_if_status_not_false',
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalespecialidad',
            name='name',
            field=models.CharField(db_index=True, max_length=30, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalmedico',
            name='code',
            field=models.CharField(db_index=True, max_length=5, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='historicalmedico',
            name='identification',
            field=models.CharField(db_index=True, max_length=9, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='historicalmedico',
            name='rif',
            field=models.CharField(db_index=True, max_length=10, verbose_name='RIF'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='code',
            field=models.CharField(max_length=5, unique=True, verbose_name='Codigo'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='identification',
            field=models.CharField(max_length=9, unique=True, verbose_name='Cédula de identidad'),
        ),
        migrations.AlterField(
            model_name='medico',
            name='rif',
            field=models.CharField(max_length=10, unique=True, verbose_name='RIF'),
        ),
    ]
