# Generated by Django 5.0.3 on 2024-04-25 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0005_rename_specialty_medico_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='is_actionist',
            field=models.BooleanField(default=False, help_text='✅ Es accionista / ❌ No es accionista', verbose_name='Es accionista'),
        ),
        migrations.AddField(
            model_name='medico',
            name='n_actions',
            field=models.IntegerField(blank=True, default=True, null=True, verbose_name='Número de acciones'),
        ),
    ]
