# Generated by Django 5.0.3 on 2024-04-05 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0006_remove_especialidad_specialty_name_unique_if_status_not_false_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmedico',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalmedico',
            name='history_user',
        ),
        migrations.DeleteModel(
            name='HistoricalEspecialidad',
        ),
        migrations.DeleteModel(
            name='HistoricalMedico',
        ),
    ]
